version: '3'
services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    ports:
      - "8080:8080"
    volumes:
      - ./docs:/docs/docs
      - ./mkdocs.yml:/docs/mkdocs.yml 