FROM python:3.11-slim

WORKDIR /docs

COPY mkdocs.yml .
COPY docs/ docs/
COPY requirements-docs.txt .

RUN pip install -r requirements-docs.txt

EXPOSE 8080

CMD ["mkdocs", "serve", "-a", "0.0.0.0:8080"]