# Generated by Django 5.0.2 on 2024-12-11 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('date_accepted', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('update_profile', 'Update Profile'), ('post', 'Create Post'), ('connect', 'Connect with user')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'action'], name='userauth_au_user_id_f60354_idx'), models.Index(fields=['timestamp'], name='userauth_au_timesta_940cd8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('connected_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'connected_user'], name='userauth_co_user_id_dfba3f_idx')],
                'unique_together': {('user', 'connected_user')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text')], max_length=20)),
                ('content', models.TextField(null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='posts/media/')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'content_type'], name='userauth_po_user_id_44343c_idx'), models.Index(fields=['created_at'], name='userauth_po_created_9a5dbb_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('x', 'X'), ('tiktok', 'Tiktok'), ('youtube', 'Youtube'), ('linkedin', 'Linkedin'), ('instagram', 'Instagram')], max_length=20)),
                ('token', models.CharField(max_length=500, null=True)),
                ('token_type', models.CharField(max_length=20, null=True)),
                ('expires', models.DateTimeField(null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('is_linked', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'platform'], name='userauth_so_user_id_9f66ce_idx'), models.Index(fields=['platform'], name='userauth_so_platfor_6c1d93_idx')],
                'unique_together': {('user', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profilePicture', models.ImageField(blank=True, default='default_pp.png', null=True, upload_to='')),
                ('qr_code', models.ImageField(blank=True, default='qr_code.png', null=True, upload_to='')),
                ('user_code', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_score', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='userauth_us_user_id_8e521d_idx'), models.Index(fields=['profile_score'], name='userauth_us_profile_7feca6_idx')],
            },
        ),
    ]
