# Generated by Django 5.0.2 on 2024-12-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='platform',
            field=models.CharField(choices=[('x', 'X'), ('google', 'Google'), ('youtube', 'Youtube'), ('tiktok', 'Tiktok'), ('instagram', 'Instagram'), ('linkedin', 'Linkedin'), ('facebook', 'Facebook')], max_length=20),
        ),
    ]
